version: '3'

services:
  bind9:
    container_name: ns1
    image: ubuntu/bind9:9.18-24.04_beta
    environment:
      - BIND9_USER=root
      - TZ=America/New_York
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      macvlan255:
        ipv4_address: 10.0.255.24
    volumes:
      - ns1_config:/etc/bind
      - ns1_cache:/var/cache/bind
      - ns1_records:/var/lib/bind
    restart: unless-stopped

networks:
  macvlan255:
    name: macvlan255
    external: true
    ipam:
     config:
       - subnet: "10.0.255.0/24"
         gateway: 10.0.255.1