services:
  macos:
    image: dockurr/macos
    container_name: macos_dockurr
    environment:
      VERSION: "15"
      DISK_SIZE: "64G"
      CPU_CORES: "4"
      RAM_SIZE: "8GB"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    networks:
      macvlan255:
        ipv4_address: 10.0.255.156
    volumes:
      - dockurr_macos_disk_1:/storage
    restart: unless-stopped
    stop_grace_period: 2m

networks:
  macvlan255:
    name: macvlan255
    external: true
    ipam:
     config:
       - subnet: "10.0.255.0/24"
         gateway: 10.0.255.1

volumes:
  dockurr_macos_disk_1:
    external: true