services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"      
    environment:
      - CF_API_EMAIL=user@example.com
      - CF_API_KEY=YOUR_API_KEY
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro

#  whoami:
#    image: "traefik/whoami"
#    container_name: "simple-service"
#    networks:
#      macvlan255:
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.whoami.entrypoints=web"
#      - "traefik.http.routers.whoami.entrypoints=websecure"
#      - "traefik.http.routers.whoami.rule=Host(`whoami.home.youngsecurity.net`)"
#      - "traefik.http.routers.whoami.tls=true"
#      - "traefik.http.routers.whoami.tls.certresolver=myresolver"