name: Test Secrets Value
on:
  # Schedule updates (each hour)
  #schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Secret Value
      run: |
        echo "The secret value is:"
        echo "${{ secrets.HOSTS }}"
