version: '3.8'

services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - mysql_root_password

  ipam:
    depends_on:
      - mysql
    image: pierrecdn/phpipam
    environment:
      MYSQL_ENV_MYSQL_USER: root
      MYSQL_ENV_MYSQL_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_ENV_MYSQL_HOST: mysql
    ports:
      - "80:80"
    secrets:
      - mysql_root_password

secrets:
  mysql_root_password:
    file: ~/.mysql_root_password.txt

volumes:
  db_data:
